.TH "construct.h" 3 "Mon Jan 13 2014" "Mars Map" \" -*- nroff -*-
.ad l
.nh
.SH NAME
construct.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconstruct\fP (\fBmap_t\fP *omap, \fBmap_t\fP *nmap)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void construct (\fBmap_t\fP *omap, \fBmap_t\fP *nmap)"
Makes the count of a map add up to the count of the original\&. 
.PP
\fBParameters:\fP
.RS 4
\fIomap\fP original map 
.br
\fInmap\fP new map 
.RE
.PP

.PP
Definition at line 10 of file construct\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Mars Map from the source code\&.
