.TH "main.c" 3 "Mon Jan 13 2014" "Mars Map" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'map\&.h'\fP
.br
\fC#include 'pyramid\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.PP
Definition at line 6 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Mars Map from the source code\&.
