.TH "map_t" 3 "Mon Jan 13 2014" "Mars Map" \" -*- nroff -*-
.ad l
.nh
.SH NAME
map_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBside\fP"
.br
.ti -1c
.RI "int \fBc_width\fP"
.br
.ti -1c
.RI "int \fBc_height\fP"
.br
.ti -1c
.RI "long int \fBcount\fP"
.br
.ti -1c
.RI "long int \fBcost\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.ti -1c
.RI "int \fBmin\fP"
.br
.ti -1c
.RI "int \fBc_max\fP"
.br
.ti -1c
.RI "int \fBc_min\fP"
.br
.ti -1c
.RI "int ** \fBmatrix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file map\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int c_height"

.PP
Definition at line 5 of file map\&.h\&.
.SS "int c_max"

.PP
Definition at line 10 of file map\&.h\&.
.SS "int c_min"

.PP
Definition at line 10 of file map\&.h\&.
.SS "int c_width"

.PP
Definition at line 5 of file map\&.h\&.
.SS "long int cost"

.PP
Definition at line 7 of file map\&.h\&.
.SS "long int count"

.PP
Definition at line 6 of file map\&.h\&.
.SS "int h"

.PP
Definition at line 8 of file map\&.h\&.
.SS "int** matrix"

.PP
Definition at line 11 of file map\&.h\&.
.SS "int max"

.PP
Definition at line 9 of file map\&.h\&.
.SS "int min"

.PP
Definition at line 9 of file map\&.h\&.
.SS "int side"

.PP
Definition at line 4 of file map\&.h\&.
.SS "int x"

.PP
Definition at line 8 of file map\&.h\&.
.SS "int y"

.PP
Definition at line 8 of file map\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mars Map from the source code\&.
