.TH "thread_data" 3 "Mon Jan 13 2014" "Mars Map" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBj\fP"
.br
.ti -1c
.RI "char * \fBstatus\fP"
.br
.ti -1c
.RI "\fBmap_t\fP * \fBmap\fP"
.br
.ti -1c
.RI "\fBmap_t\fP ** \fBbest\fP"
.br
.ti -1c
.RI "pthread_mutex_t * \fBlock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file map\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBmap_t\fP** best"

.PP
Definition at line 20 of file map\&.h\&.
.SS "int i"

.PP
Definition at line 16 of file map\&.h\&.
.SS "int j"

.PP
Definition at line 17 of file map\&.h\&.
.SS "pthread_mutex_t* lock"

.PP
Definition at line 21 of file map\&.h\&.
.SS "\fBmap_t\fP* map"

.PP
Definition at line 19 of file map\&.h\&.
.SS "char* status"

.PP
Definition at line 18 of file map\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mars Map from the source code\&.
